[package]
name = "hotreload_macros"
version = "0.1.0"
authors = ["Nico Chatzi <nico.chatzigianis@focusrite.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/nicochatzi/hotreload-rs"
readme = "README.md"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.9"